### PR TITLE
`declare_widget` makes a struct now

### LINKED ISSUE #27: Have declare_widget generate a struct instead of a tuple
In current code, calling `declare_widget!(FoobarMut, Foobar)` will generate `FoobarMut` as a tuple of a `WidgetState` and a `Foobar`. It should instead be a struct with these two fields, with names like "state" and "widget", for clearer widget code.

### LINKED ISSUE #354: Have declare_widget generate a struct instead of a tuple
In current code, calling `declare_widget!(FoobarMut, Foobar)` will generate `FoobarMut` as a tuple of a `WidgetState` and a `Foobar`. It should instead be a struct with these two fields, with names like "state" and "widget", for clearer widget code.

### PR DESCRIPTION
**Pull request by TmLev**
Should resolve linebender/xilem#354.

### CODE REVIEW

**Comment by TmLev** [comment]
I was trying to run `cargo test` in order to ensure that nothing broke, but there were compilation errors even before I made any changes:

```logs
❯ cargo test
   Compiling masonry v0.1.2 (/Users/lev/repos/masonry-rs)
error[E0609]: no field `inner` on type `&AppRootInner`
   --> src/app_root.rs:846:14
    |
846 |         self.inner.borrow().app.hide()
    |              ^^^^^ unknown field
    |
    = note: available fields are: `app_handle`, `debug_logger`, `app_delegate`, `command_queue`, `action_queue` ... and 8 others

error[E0609]: no field `inner` on type `&mut AppRootInner`
   --> src/app_root.rs:852:14
    |
852 |         self.inner.borrow().app.hide_others();
    |              ^^^^^ unknown field
    |
    = note: available fields are: `app_handle`, `debug_logger`, `app_delegate`, `command_queue`, `action_queue` ... and 8 others

For more information about this error, try `rustc --explain E0609`.
error: could not compile `masonry` due to 2 previous errors
warning: build failed, waiting for other jobs to finish...
error: could not compile `masonry` due to 2 previous errors
```

**Comment by PoignardAzur** [comment]
That's odd. I'll check it ASAP.

EDIT: `cargo build --all-targets && cargo test` passes on my machine.

**Review by PoignardAzur — CHANGES_REQUESTED** [review]
Thanks for your contribution!

The changeset looks good.

One request: the first field is a `WidgetCtx`, so it should be called `ctx` or `context` or something like it.

**Comment by PoignardAzur** [comment]
Compilation worked for me on a fresh clone. That's odd.

Can you apply the standard steps:

- Remove the `target/` dir and recompile,
- Check that your clone is clear,
- Check that your current commit is the same as origin/master?

If it still fails, what OS are you on, what Rust version do you use, etc?

**Comment by TmLev** [comment]
> That's odd. I'll check it ASAP.
> 
> EDIT: `cargo build --all-targets && cargo test` passes on my machine.

Does your machine run macOS? Mine does. There is a `cfg` for macOS: https://github.com/PoignardAzur/masonry-rs/blob/6eaf0071a6a55945f0c095e38138c8b0a227c7f1/src/app_root.rs#L843-L846

**Comment by TmLev** [comment]
> One request: the first field is a `WidgetCtx`, so it should be called `ctx` or `context` or something like it.

I took the names from the original issue which suggested `widget` and `state` :)
Gonna change that to `ctx`, one moment.

**Comment by PoignardAzur** [comment]
> Does your machine run macOS? Mine does. There is a cfg for macOS: 

Oooooh. That explains it.

**Comment by PoignardAzur** [comment]
Alright, will try to merge your PR tomorrow.

**Comment by TmLev** [comment]
Let me know if there is anything else you need for this PR.

**Comment by PoignardAzur** [comment]
Sorry, I was a bit more busy than expected.

I'd like to run proper CI and your changes before merging them, but I need to fix the CI first. Otherwise your PR looks ready to merge.

**Review by PoignardAzur — APPROVED** [review]

**Comment by PoignardAzur** [comment]
Can you rebase your branch on the current head and push again? Most CI problems should be fixed now.

(Otherwise, I'll merge this in a few days.)

**Comment by TmLev** [comment]
Rebased. 

Seems like some tests are failing. I've checked the `main` branch and the same tests fail there, too.

```logs
failures:
    widget::align::tests::centered
    widget::align::tests::left
    widget::align::tests::right
    widget::button::tests::simple_button
    widget::checkbox::tests::simple_checkbox
    widget::flex::tests::flex_col_cross_axis_snapshots
    widget::flex::tests::flex_col_main_axis_snapshots
    widget::flex::tests::flex_row_cross_axis_snapshots
    widget::flex::tests::flex_row_main_axis_snapshots
    widget::label::tests::line_break_modes
    widget::label::tests::simple_label
    widget::label::tests::styled_label
    widget::portal::tests::button_list
    widget::scroll_bar::tests::horizontal_scrollbar
    widget::scroll_bar::tests::simple_scrollbar
    widget::sized_box::tests::empty_box
    widget::sized_box::tests::label_box_no_size
    widget::sized_box::tests::label_box_with_size
    widget::spinner::tests::simple_spinner
    widget::split::tests::columns
    widget::split::tests::rows
    widget::textbox::tests::simple_textbox
    widget::textbox::tests::simple_textbox_placeholder

test result: FAILED. 93 passed; 23 failed; 0 ignored; 0 measured; 0 filtered out; finished in 1.11s
```

**Comment by PoignardAzur** [comment]
Most of the CI tests pass, and the ones that fail also fail on main. I'll merge now, and take care of the test flakiness later.

**Pull request merged**
