### PR TITLE
Fix Textbox text position and Textbox size

### PR DESCRIPTION
**Pull request by bitec0de**
If I type 'o' and press left arrow, it looks like this because the text is positioned without regard to textbox insets:

masonry textbox cursor error

Also, the Textbox is too small, cutting off the bottom of descender characters like 'j' and 'y'.

### CODE REVIEW

**Comment by PoignardAzur** [comment]
Thanks for the bug reports!

The current Textbox implementation is hacked together from the remains of druid's, so it definitely needs a rewriting pass.

**Comment by PoignardAzur** [comment]
Wait, no, this is a PR. I assume it was an issue filing.

The code changes look good, but you're going to need to update the screenshot tests.

**Comment by PoignardAzur** [comment]
I've bypassed the tests, since all of them passed except one on windows which is currently flaky.

Thank you for the PR!

**Comment by bitec0de** [comment]
No problem, thank you for the project!

**Pull request merged**
